name: Deploy - Vercel

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Format/Lint code
        uses: ./.github/actions/format-lint-code

      - name: Run unit tests
        uses: ./.github/actions/unit-tests

      - name: Build app
        run: npm run build

      - name: Deploy app to Vercel production env
        uses: ./.github/actions/deploy-vercel
        with:
          mode: 'production'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  e2e-tests:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
    steps:
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          BASE_URL: 'https://cicd-crud-vue.vercel.app/'
